package grouplogic.citywatch;

import android.net.Uri;
import android.os.Bundle;
import android.app.Activity;
import android.content.Intent;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;

public class EmailEditor extends Activity {

	private String emailAddress;
	private String sendTo;
	private String issue;
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_email);
		
		Intent intent = getIntent();
		
		emailAddress = intent.getStringExtra("emailAddress");
		sendTo = intent.getStringExtra("sendTo");
		issue = intent.getStringExtra("issue");
		
		TextView sendToView = (TextView) findViewById(R.id.sendTo);
		TextView issueView = (TextView) findViewById(R.id.issue);
		
		sendToView.setText("Send To: " + sendTo);
		issueView.setText("Issue: " + issue);
	}
	
	
    public void sendEmail(View view) {
        Intent intent = new Intent(Intent.ACTION_SENDTO, Uri.parse("mailto:" + emailAddress));
        intent.putExtra(Intent.EXTRA_SUBJECT, "Issue: " + issue);
        
        EditText comments = (EditText) findViewById(R.id.comments);
        intent.putExtra(Intent.EXTRA_TEXT,  "This message is generated by the CityWatch Android app and contains a message to: " + sendTo
        									+ "\n\n" + comments.getText().toString());

        startActivity(Intent.createChooser(intent,  "Send Email"));
    }
    

	/*
	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.email, menu);
		return true;
	}
	*/
}
